---
- hosts: all
  gather_facts: no
  vars:
    color: brown
    gac_dir: /vol/fou/sicci1/data/gacrepr1/pps_v1
    # project_dir: /disk1/workspace/ice-arc
    project_dir: ~/ice-arc
    venv: "{{ project_dir }}/codeshop/icearc-avhrr-sic/venv-vagrant"

  tasks:

  - name: Install virtualenv
    apt: name={{ item }} state=present update_cache=yes
    sudo: true
    sudo_user: root
    with_items:
      - git
      - python-dev
      - libhdf5-serial-dev

  - name: Create project directory
    file: path={{ project_dir }} state=directory

  - name: Update pip
    pip: virtualenv={{ venv }} name={{ item }} extra_args='--upgrade'
    with_items:
      - pip
      - behave
      - PyYAML

  - name: Install behave
    pip: name=behave virtualenv={{ venv }}

  - name: Install pypps_reader
    pip: name='git+https://github.com/mitkin/pypps_reader.git#egg=pypps_reader' virtualenv={{ venv }}
