---
- hosts: all
  gather_facts: no
  user: "{{ dp_user }}"
  sudo_user: root
  vars:
    user: "{{ dp_user }}"
    home_dir: "/home/{{ dp_user }}"
    base_dir: "{{ base_dir }}"
    local_gac_dir: "{{ base_dir }}/data/gac"
    local_sic_dir: "{{ base_dir }}/data/sic"
    venv: "{{ base_dir }}/.virtualenvs/ice-arc"
    test_date: "20080801"
    wip_branch: master # name of the branch to clone

  tasks:

  - name: Install system dependencies
    apt: name={{ item }} state=present update_cache=yes
    sudo: true
    sudo_user: root
    with_items:
      - git
      - python-dev
      - libhdf5-serial-dev
      - libnetcdf-dev
      - sshfs
    tags:
      - apt

  - name: Create project directory
    file: path={{ base_dir }} state=directory
    tags:
      - dir

  - name: Get the code from gitlab
    # assume vagrant.pub key has been copied over to the destination
    git: repo=git@gitlab.com:mitkin/icearc-avhrr-sic.git
         dest="{{ base_dir }}/codeshop"
         accept_hostkey=yes
         version={{ wip_branch }}
         force=yes key_file="{{ home_dir }}/.ssh/vagrant.pub"
         recursive=yes
    tags:
      - git

  - name: Update pip
    pip: virtualenv={{ venv }} name={{ item }}
         virtualenv_site_packages=yes
    with_items:
      - pip
      - behave
      - PyYAML
      - numpy
      - netCDF4
      - python-dateutil
    tags:
      - pip

  - name: Install pypps_reader
    pip: name='git+https://github.com/mitkin/pypps_reader.git#egg=pypps_reader'
         virtualenv={{ venv }}
    tags:
      - pip


  - name: Create GAC data folder
    file: path="{{ local_gac_dir }}" state=directory
    tags:
      - gacdata

  - name: Download gac data
    get_url: url=https://www.dropbox.com/s/ms5wysnqd07xjvg/gac-data.tar.gz?dl=1 dest="{{ local_gac_dir}}/gac-data.tar.gz"
    tags:
      - gacdata

  - name: Unarchive GAC data
    unarchive: src="{{ local_gac_dir }}/gac-data.tar.gz"
               dest="{{ local_gac_dir }}"
               copy=no
    tags:
      - gacdata

  - name: Create SIC folder
    file: path="{{ local_sic_dir }}" state=directory
    tags:
      - sicdata

  - name: Downlad SIC data OSI SAF
    get_url: url=ftp://osisaf.met.no/reprocessed/ice/conc/v1p2/2008/08/ice_conc_nh_polstere-100_reproc_200808011200.nc.gz
             dest="{{ local_sic_dir }}/sic-data.gz"
    tags:
      - sicdata

  - name: Uncompress SIC data
    shell: gzip -d -f "{{ local_sic_dir }}/sic-data.gz"
    tags:
      - sicdata


  - name: Run behaviour tests
    shell: "{{ venv }}/bin/behave --tags=wip"
    args:
      chdir: "{{ base_dir }}/codeshop"
    tags:
      - tests
