---
- hosts: all
  gather_facts: no
  user: "{{ dp_user }}"
  sudo_user: root
  vars:
    user: "{{ dp_user }}"
    home_dir: "/home/{{ dp_user }}"
    project_dir: "{{ home_dir }}/ice-arc"
    data_dir: "{{ project_dir }}/data"
    venv: "{{ home_dir }}/.virtualenvs/ice-arc"
    test_date: "20080701"
    wip_branch: master # name of the branch to clone

  tasks:

  - name: Install system dependencies
    apt: name={{ item }} state=present update_cache=yes
    sudo: true
    sudo_user: root
    with_items:
      - git
      - python-dev
      - libhdf5-serial-dev
      - libnetcdf-dev
      - sshfs
    tags:
      - apt

  - name: Create project directory
    file: path={{ project_dir }} state=directory
    tags:
      - dir

  - name: Update pip
    pip: virtualenv={{ venv }} name={{ item }}
         virtualenv_site_packages=yes
    with_items:
      - pip
      - behave
      - PyYAML
      - numpy
      - netCDF4
      - python-dateutil
    tags:
      - pip

  - name: Install pypps_reader
    pip: name='git+https://github.com/mitkin/pypps_reader.git#egg=pypps_reader'
         virtualenv={{ venv }}
    tags:
      - pip

  - name: Get the code from gitlab
    # assume vagrant.pub key has been copied over to the destination
    git: repo=git@gitlab.com:mitkin/icearc-avhrr-sic.git
         dest="{{ project_dir }}/codeshop/icearc-avhrr-sic"
         accept_hostkey=yes
         version={{ wip_branch }}
         force=yes key_file="{{ home_dir }}/.ssh/vagrant.pub"
         recursive=yes
    tags:
      - git

  - name: Create GAC data folder
    file: path="{{ data_dir }}/gac" state=directory
    tags:
      - gacdata

  - name: Download gac data
    get_url: url=https://www.dropbox.com/s/ms5wysnqd07xjvg/gac-data.tar.gz?dl=1 dest="{{ data_dir}}/gac/gac-data.tar.gz"
    tags:
      - gacdata

  - name: Unarchive GAC data
    unarchive: src="{{ data_dir }}/gac/gac-data.tar.gz"
               dest="{{ data_dir }}/gac"
               copy=no
    tags:
      - gacdata

  - name: Run behaviour tests
    shell: "{{ venv }}/bin/behave --tags=wip"
    args:
      chdir: "{{ project_dir }}/codeshop/icearc-avhrr-sic"
    tags:
      - tests
