---
- hosts: all
  gather_facts: no
  user: "{{ dp_user }}"
  sudo_user: root
  vars:
    user: "{{ dp_user }}"
    color: brown
    remote_gac_dir: /vol/fou/sicci1/data/gacrepr1/pps_v1
    remote_sic_dir: /vol/fou/sicci1/data/NSIDC-SeaIce-CDR-v2/2008
    local_gac_dir: /disk1/gac-data
    local_sic_dir: /disk1/sic-data
    # project_dir: /disk1/workspace/ice-arc
    project_dir: "/home/{{ dp_user }}/ice-arc"
    venv: "{{ project_dir }}/codeshop/icearc-avhrr-sic/venv-vagrant"

  tasks:
  - name: Install virtualenv
    apt: name={{ item }} state=present update_cache=yes
    sudo: true
    sudo_user: root
    with_items:
      - git
      - python-dev
      - libhdf5-serial-dev
      - sshfs
    tags:
      - apt

  - name: Create project directory
    file: path={{ project_dir }} state=directory

  - name: Update pip
    pip: virtualenv={{ venv }} name={{ item }} extra_args='--upgrade'
    with_items:
      - pip
      - behave
      - PyYAML
      - netCDF4

  - name: Install pypps_reader
    pip: name='git+https://github.com/mitkin/pypps_reader.git#egg=pypps_reader'
         virtualenv={{ venv }}

  - name: Get ICE ARC code from git
    git: repo=git@gitlab.met.no:istjenesten/icearc-avhrr-sic.git
         dest=~/icearc-avhrr-sic
         accept_hostkey=yes
         force=yes key_file="{{ lookup('file', '/home/mikhaili/.ssh/metno.pub') }}"
    tags:
      - git

  - name: Make a mount point
    file: path={{ local_gac_dir }} state=directory owner={{ user}}
    sudo: true
    ignore_errors: true
    tags:
      - ssh

  - name: Mount data directory
    shell: sshfs "mikhaili@{{ gac_data_host }}:{{ remote_gac_dir }}" {{ local_gac_dir }} -o reconnect
    ignore_errors: true
    tags:
      - ssh

  - name: Mount data directory
    shell: sshfs "mikhaili@{{ gac_data_host }}:{{ remote_sic_dir }}" {{ local_sic_dir }} -o reconnect
    ignore_errors: true
    tags:
      - ssh

  - name: Run behaviour tests
    shell: "{{ venv }}/bin/behave"
    args:
      chdir: ~/icearc-avhrr-sic
    tags:
      - tests
