---
- hosts: all
  gather_facts: no
  user: "{{ dp_user }}"
  sudo_user: root
  vars:
    user: "{{ dp_user }}"
    remote_gac_dir: /vol/fou/sicci1/data/gacrepr1/pps_v1
    remote_sic_dir: /vol/fou/sicci1/data/NSIDC-SeaIce-CDR-v2/2008
    local_gac_dir: /disk1/gac-data
    local_sic_dir: /disk1/sic-data
    home_dir: "/home/{{ dp_user }}"
    project_dir: "{{ home_dir }}/ice-arc"
    venv: "{{ project_dir }}/codeshop/venv"
    test_date: "20080701"
    wip_branch: behave_compute-sic_feature # name of the branch to clone

  tasks:

  - name: Install system dependencies
    apt: name={{ item }} state=present update_cache=yes
    sudo: true
    sudo_user: root
    with_items:
      - git
      - python-dev
      - libhdf5-serial-dev
      - libnetcdf-dev
      - sshfs
    tags:
      - apt

  - name: Create project directory
    file: path={{ project_dir }} state=directory

  - name: Update pip
    pip: virtualenv={{ venv }} name={{ item }}
         virtualenv_site_packages=yes
    with_items:
      - pip
      - behave
      - PyYAML
      - netCDF4
      - python-dateutil
    tags:
      - pip

  - name: Install pypps_reader
    pip: name='git+https://github.com/mitkin/pypps_reader.git#egg=pypps_reader'
         virtualenv={{ venv }}
    tags:
      - pip

  - name: Get the code from gitlab
    # assume vagrant.pub key has been copied over to the destination
    git: repo=git@gitlab.com/mitkin/icearc-avhrr-sic.git
         dest="{{ project_dir }}/codeshop/icearc-avhrr-sic"
         accept_hostkey=yes
         version={{ wip_branch }}
         force=yes key_file="{{ home_dir }}/.ssh/vagrant.pub"
         track_submodules=yes recursive=yes
    tags:
      - git

  - name: Run behaviour tests
    shell: "{{ venv }}/bin/behave --tags=wip"
    args:
      chdir: "{{ project_dir }}/codeshop/icearc-avhrr-sic"
    tags:
      - tests
